name: Package Factorio Mod

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Package mod
      run: |
        python -c "
        import zipfile
        import os
        from zipfile import ZipFile

        def get_mod_version():
            with open('GunfireReplacer/info.json', 'r') as f:
                import json
                return json.load(f)['version']

        def zipdir(path, ziph):
            for root, dirs, files in os.walk(path):
                for file in files:
                    ziph.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), os.path.join(path, '..')))

        mod_name = 'GunfireReplacer'
        mod_version = get_mod_version()
        mod_directory = f'{mod_name}_{mod_version}'

        os.rename(mod_name, mod_directory)

        zipf = zipfile.ZipFile(f'{mod_directory}.zip', 'w', zipfile.ZIP_DEFLATED)
        zipdir(mod_directory, zipf)
        zipf.close()

        os.rename(mod_directory, mod_name)
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: GunfireReplacer
        path: GunfireReplacer_*.zip
